# [loggers]
# keys=root,sampleLogger

# [handlers]
# keys=consoleHandler
version: 1
formatters:
    simple:
        format: '%(asctime)s - %(levelname)s : %(module)s : %(funcName)s : %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file_handler:
        class: logging.FileHandler
        level: DEBUG
        formatter: simple
        filename: logs/all_messages.log
loggers:
    sampleLogger:
        level: DEBUG
        handlers: [file_handler]
        propagate: no
root:
    level: DEBUG
    handlers: [console]
